- id: button_1_single
  alias: Button single
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/button_1
  condition:
    condition: template
    value_template: >-
      {{ trigger.payload_json.click == 'single' }}
  action:
    service: light.toggle
    data:
      entity_id: light.living_room

- id: button_1_double
  alias: Button double
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/button_1
  condition:
    condition: template
    value_template: >-
      {{ trigger.payload_json.click == 'double' }}
  action:
    service: media_player.toggle
    data:
      entity_id: media_player.tv

- id: button_1_long
  alias: Button long
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/button_1
  condition:
    condition: template
    value_template: >-
      {{ trigger.payload_json.click == 'long' }}
  action:
    service: switch.toggle
    data:
      entity_id: switch.reading_living_room

- id: button_2_single
  alias: Button 2 single
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/button_2
  condition:
    - condition: template
      value_template: >-
        {{ trigger.payload_json.click == 'single' }}
    - condition: time
      after: '08:00'
      before: '21:00'
  action:
    service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: !secret ac_partner_mac
      ringtone_id: 10
      ringtone_vol: 50

- id: climate_bedroom_auto_off_cold
  alias: Climate bedroom auto off when cold
  trigger:
    platform: numeric_state
    entity_id: sensor.ht_bedroom_temperature
    below: 25
  condition:
    condition: numeric_state
    entity_id: sensor.ht_outside_temperature
    below: 25
  action:
    service: climate.set_operation_mode
    data:
      entity_id: climate.bedroom
      operation_mode: 'off'

- id: climate_bedroom_auto_off_door_open
  alias: Climate bedroom auto off when door open
  trigger:
    platform: state
    entity_id: binary_sensor.door_bedroom
    to: 'on'
    for: '00:02:00'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom
        operation_mode: 'off'
    - delay: '00:00:10'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom
        operation_mode: 'off'
    - delay: '00:00:10'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom
        operation_mode: 'off'

- id: climate_bedroom_auto_cool
  alias: Climate bedroom auto cool
  trigger:
    platform: state
    entity_id: binary_sensor.door_bedroom
    to: 'off'
    for: '00:00:10'
  condition:
    - condition: numeric_state
      entity_id: sensor.ht_bedroom_temperature
      above: 26.8
    - condition: numeric_state
      entity_id: sensor.ht_outside_temperature
      above: 26.8
  action:
    service: climate.set_operation_mode
    data:
      entity_id: climate.bedroom
      operation_mode: cool

- id: cube_flip90
  alias: Cube flip90
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/cube
  condition:
    condition: template
    value_template: >-
      {{ trigger.payload_json.action == 'flip90' }}
  action:
    service: switch.toggle
    data:
      entity_id: switch.reading_living_room

# - id: cube_rotate_left
#   alias: Cube rotate left
#   trigger:
#     platform: mqtt
#     topic: zigbee2mqtt/cube
#   condition:
#     condition: template
#     value_template: >-
#       {{ trigger.payload_json.action == 'rotate_left' }}
#   action:
#     service: light.turn_on
#     entity_id: light.living_room
#     data_template:
#       brightness: >-
#         {{ states.light.living_room.attributes.brightness - 50 }}

# - id: cube_rotate_right
#   alias: Cube rotate right
#   trigger:
#     platform: mqtt
#     topic: zigbee2mqtt/cube
#   condition:
#     condition: template
#     value_template: >-
#       {{ trigger.payload_json.action == 'rotate_right' }}
#   action:
#     service: light.turn_on
#     entity_id: light.living_room
#     data_template:
#       brightness: >-
#         {{ states.light.living_room.attributes.brightness + 50 }}

- id: light_living_room_auto_off
  alias: Light living room auto off
  trigger:
    platform: state
    entity_id: binary_sensor.occupancy_living_room
    to: 'off'
    for: '00:03:00'
  condition:
    condition: time
    after: '23:00'
    before: '18:00'
  action:
    service: light.turn_off
    data:
      entity_id: light.living_room

- id: light_living_room_auto_on
  alias: Light living room auto on
  trigger:
    platform: state
    entity_id: binary_sensor.occupancy_living_room
    to: 'on'
  condition:
    condition: time
    after: '07:00'
    before: '00:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.living_room

- id: light_living_room_auto_midnight
  alias: Light living room auto on midnight
  trigger:
    platform: state
    entity_id: binary_sensor.occupancy_living_room
    to: 'on'
  condition:
    condition: time
    after: '00:00'
    before: '07:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.living_room
      brightness: 1

- id: moonlight_living_room_auto_on_off
  alias: Moonlight living room auto on off
  trigger:
    - platform: state
      entity_id: binary_sensor.door_bedroom
      to: 'off'
    - platform: state
      entity_id: binary_sensor.door_bedroom
      to: 'on'
  condition:
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: time
      after: '22:00'
      before: '08:30'
  action:
    service_template: >-
      input_boolean.turn_{{ states(trigger.entity_id) }}
    data:
      entity_id: input_boolean.moonlight_living_room

- id: moonlight_living_room_off
  alias: Moonlight living room off
  hide_entity: yes
  trigger:
    platform: state
    entity_id: input_boolean.moonlight_living_room
    to: 'off'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.flux_living_room

- id: moonlight_living_room_on
  alias: Moonlight living room on
  hide_entity: yes
  trigger:
    platform: state
    entity_id: input_boolean.moonlight_living_room
    to: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.flux_living_room
    - service: light.yeelight_set_mode
      data:
        entity_id: light.living_room
        mode: moonlight
    # - service: light.turn_on
    #   entity_id: light.living_room
    #   data:
    #     brightness: 255

- id: flux_living_room_light_on
  alias: Flux living room light on
  trigger:
    platform: state
    entity_id: light.living_room
    to: 'on'
  condition:
    condition: time
    after: '7:00'
    before: '23:00'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.flux_living_room

- id: flux_living_room_hass_started
  alias: Flux living room hass started
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: time
    after: '22:00'
    before: '17:00'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.flux_living_room

# - id: nightlight_bedroom_auto_off
#   alias: Nightlight bedroom auto off
#   trigger:
#     platform: state
#     entity_id: binary_sensor.motion_living_room
#     to: 'off'
#     for: '00:30:00'
#   action:
#     service: switch.turn_off
#     data:
#       entity_id: switch.plug_switch

# - id: nightlight_bedroom_auto_on
#   alias: Nightlight bedroom auto on
#   trigger:
#     platform: state
#     entity_id: binary_sensor.motion_living_room
#     to: 'on'
#   condition:
#     - condition: sun
#       after: sunset
#   action:
#     service: switch.turn_on
#     data:
#       entity_id: switch.plug_switch

- id: notify_home
  alias: Notify home
  trigger:
    platform: state
    entity_id:
      - device_tracker.owntracks_2
    from: not_home
    to: home
  condition:
    condition: time
    after: '8:00'
    before: '21:00'
  action:
    service: notify.html5
    data_template:
      message: >-
        {{ state_attr(trigger.entity_id, 'friendly_name') }} arrived home

- id: theme_custom
  alias: Set custom theme at startup
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: custom

- id: water_heater
  alias: Water heater
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.water_heater

- id: water_heater_season
  alias: Water heater season
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    condition: template
    value_template: >-
      {{ not is_state('sensor.season', 'summer')  }}
  action:
    service: switch.turn_on
    data:
      entity_id: switch.water_heater
