##### Button #####

- alias: Button 1 single
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/button_1
  condition:
    condition: template
    value_template: >-
      {{ trigger.payload_json.click == 'single' }}
  action:
    service: light.toggle
    data:
      entity_id: light.living_room

- alias: Button 1 double
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/button_1
  condition:
    condition: template
    value_template: >-
      {{ trigger.payload_json.click == 'double' }}
  action:
    service: media_player.toggle
    data:
      entity_id: media_player.tv

- alias: Button 1 long
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/button_1
  condition:
    condition: template
    value_template: >-
      {{ trigger.payload_json.click == 'long' }}
  action:
    service: switch.toggle
    data:
      entity_id: switch.reading_living_room

- alias: Button 2 single
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/button_2
  condition:
    - condition: template
      value_template: >-
        {{ trigger.payload_json.click == 'single' }}
    - condition: time
      after: '08:00'
      before: '21:00'
  action:
    service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: !secret ac_partner_mac
      ringtone_id: 10
      ringtone_vol: 50

- alias: Cube flip90
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/cube
  condition:
    condition: template
    value_template: >-
      {{ trigger.payload_json.action == 'flip90' }}
  action:
    service: switch.toggle
    data:
      entity_id: switch.reading_living_room

# - alias: Cube rotate left
#   trigger:
#     platform: mqtt
#     topic: zigbee2mqtt/cube
#   condition:
#     condition: template
#     value_template: >-
#       {{ trigger.payload_json.action == 'rotate_left' }}
#   action:
#     service: light.turn_on
#     entity_id: light.living_room
#     data_template:
#       brightness: >-
#         {{ states.light.living_room.attributes.brightness - 50 }}

# - alias: Cube rotate right
#   trigger:
#     platform: mqtt
#     topic: zigbee2mqtt/cube
#   condition:
#     condition: template
#     value_template: >-
#       {{ trigger.payload_json.action == 'rotate_right' }}
#   action:
#     service: light.turn_on
#     entity_id: light.living_room
#     data_template:
#       brightness: >-
#         {{ states.light.living_room.attributes.brightness + 50 }}

##### Climate #####

- alias: Climate bedroom off when cold
  trigger:
    platform: numeric_state
    entity_id: sensor.ht_bedroom_temperature
    below: 25
  condition:
    condition: numeric_state
    entity_id: sensor.ht_outside_temperature
    below: 25
  action:
    service: climate.set_operation_mode
    data:
      entity_id: climate.bedroom
      operation_mode: 'off'

- alias: Climate bedroom off when door open
  trigger:
    platform: state
    entity_id: binary_sensor.door_bedroom
    to: 'on'
    for: '00:02:00'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom
        operation_mode: 'off'
    - delay: '00:00:10'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom
        operation_mode: 'off'
    - delay: '00:00:10'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom
        operation_mode: 'off'

- alias: Climate bedroom cool when door close
  trigger:
    platform: state
    entity_id: binary_sensor.door_bedroom
    to: 'off'
    for: '00:00:10'
  condition:
    - condition: numeric_state
      entity_id: sensor.ht_bedroom_temperature
      above: 26.8
    - condition: numeric_state
      entity_id: sensor.ht_outside_temperature
      above: 26.8
  action:
    service: climate.set_operation_mode
    data:
      entity_id: climate.bedroom
      operation_mode: cool

##### HomeAssistant #####

- alias: Set custom theme at startup
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: custom

##### Flux #####

- alias: Flux living room off
  trigger:
    platform: time
    at: '23:00'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.flux_living_room

- alias: Flux living room on
  trigger:
    platform: time
    at: '7:00'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.flux_living_room

- alias: Flux living room on when hass start
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: time
    after: '7:00'
    before: '23:00'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.flux_living_room

##### Light #####

- alias: Light living room off when occupancy off
  trigger:
    platform: state
    entity_id: binary_sensor.occupancy_living_room
    to: 'off'
    for: '00:03:00'
  condition:
    condition: time
    after: '23:00'
    before: '18:00'
  action:
    service: light.turn_off
    data:
      entity_id: light.living_room

- alias: Light living room on when occupancy on
  trigger:
    platform: state
    entity_id: binary_sensor.occupancy_living_room
    to: 'on'
  condition:
    condition: time
    after: '07:00'
    before: '00:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.living_room

- alias: Light living room on when occupancy on midnight
  trigger:
    platform: state
    entity_id: binary_sensor.occupancy_living_room
    to: 'on'
  condition:
    condition: time
    after: '00:00'
    before: '07:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.living_room
      brightness: 1

- alias: Moonlight living room off when door open
  trigger:
    platform: state
    entity_id: binary_sensor.door_bedroom
    to: 'on'
    for: '00:00:15'
  condition:
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: time
      after: '22:00'
      before: '08:30'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.moonlight_living_room

- alias: Moonlight living room on off when door on off
  trigger:
    - platform: state
      entity_id: binary_sensor.door_bedroom
      to: 'off'
    - platform: state
      entity_id: binary_sensor.door_bedroom
      to: 'on'
  condition:
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: time
      after: '22:00'
      before: '08:30'
  action:
    service_template: >-
      input_boolean.turn_{{ states(trigger.entity_id) }}
    data:
      entity_id: input_boolean.moonlight_living_room

- alias: Moonlight living room off
  hide_entity: yes
  trigger:
    platform: state
    entity_id: input_boolean.moonlight_living_room
    to: 'off'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.flux_living_room

- alias: Moonlight living room on
  hide_entity: yes
  trigger:
    platform: state
    entity_id: input_boolean.moonlight_living_room
    to: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.flux_living_room
    - service: light.yeelight_set_mode
      data:
        entity_id: light.living_room
        mode: moonlight
    # - service: light.turn_on
    #   entity_id: light.living_room
    #   data:
    #     brightness: 255

# - alias: Nightlight bedroom auto off
#   trigger:
#     platform: state
#     entity_id: binary_sensor.motion_living_room
#     to: 'off'
#     for: '00:30:00'
#   action:
#     service: switch.turn_off
#     data:
#       entity_id: switch.plug_switch

# - alias: Nightlight bedroom auto on
#   trigger:
#     platform: state
#     entity_id: binary_sensor.motion_living_room
#     to: 'on'
#   condition:
#     - condition: sun
#       after: sunset
#   action:
#     service: switch.turn_on
#     data:
#       entity_id: switch.plug_switch

##### Notification #####

- alias: Notify home
  trigger:
    platform: state
    entity_id:
      - device_tracker.owntracks_2
    from: not_home
    to: home
  condition:
    condition: time
    after: '8:00'
    before: '21:00'
  action:
    service: notify.html5
    data_template:
      message: >-
        {{ state_attr(trigger.entity_id, 'friendly_name') }} arrived home

##### Water heater #####

- alias: Water heater
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.water_heater

- alias: Water heater season
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    condition: template
    value_template: >-
      {{ not is_state('sensor.season', 'summer')  }}
  action:
    service: switch.turn_on
    data:
      entity_id: switch.water_heater

##### Voice #####

- alias: Start hotword detection when hass start
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: state
    entity_id: device_tracker.owntracks_1
    state: home
  action:
    service: hotword_snowboy.listen

- alias: Start hotword detection when home
  trigger:
    platform: state
    entity_id: device_tracker.owntracks_1
    to: home
  condition:
    condition: state
    entity_id:  hotword_snowboy.decoder
    state: idle
  action:
    service: hotword_snowboy.listen

- alias: Stop hotword detection when away
  trigger:
    platform: state
    entity_id: device_tracker.owntracks_1
    to: not_home
  action:
    service: hotword_snowboy.terminate

- alias: Hotword activate web speech
  trigger:
    platform: event
    event_type: hotword_detected
  action:
    - service: wav_paplay.play_wav
      data:
        filename: wav/wakeup.wav
    - service: web_speech.listen

- alias: Shake cube activate web speech
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/cube
  condition:
    condition: template
    value_template: >-
      {{ trigger.payload_json.action == 'shake' }}
  action:
    - service: wav_paplay.play_wav
      data:
        filename: wav/wakeup.wav
    - service: web_speech.listen

# - alias: Play sound when web speech listen
#   trigger:
#     platform: state
#     entity_id: web_speech.web_speech
#     to: listening
#   action:
#     service: wav_paplay.play_wav
#     data:
#       filename: wav/wakeup.wav

- alias: Start hotword detection when web speech finish
  trigger:
    platform: event
    event_type: speech_to_text
  action:
    service: hotword_snowboy.listen

- alias: Say pardon
  trigger:
    platform: event
    event_type: speech_to_text
  condition:
    condition: template
    value_template: >-
      {{ trigger.event.data['text'] == '' }}
  action:
    service: script.say
    data:
      message: 没有听清

- alias: Process conversation
  trigger:
    platform: event
    event_type: speech_to_text
  condition:
    condition: template
    value_template: >-
      {{ trigger.event.data['text'] != '' }}
  action:
    service: conversation.process
    data_template:
      text: >-
        {{ trigger.event.data['text'] }}
