homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: Asia/Shanghai
  unit_system: metric
  customize: !include customize.yaml
  packages: !include_dir_named packages

frontend:
  themes:
    custom:
      state-icon-active-color: '#F57F17'

config:

http:
  server_host: 127.0.0.1

updater:
  reporting: no

# discovery:

conversation:
  intents:
    turn_on:
      - 打开{item}
    turn_off:
      - 关掉{item}
      - 关闭{item}

history:

hotword_snowboy:
  model: snowboy/alexa.umdl

intent_script:
  turn_on:
    speech:
      text: 已打开{{ item }}
    action:
      service: homeassistant.turn_on
      data_template:
        entity_id: >-
          {% if item | regex_match('电视') %}
            media_player.tv
          {% elif item | regex_match('(客厅|吸顶)') %}
            light.living_room
          {% elif item | regex_match('空调') %}
            switch.climate_living_room
          {% elif item | regex_match('热水') %}
            switch.water_heater
          {% endif %}
  turn_off:
    speech:
      text: 已关闭{{ item }}
    action:
      service: homeassistant.turn_off
      data_template:
        entity_id: >-
          {% if item | regex_match('电视') %}
            media_player.tv
          {% elif item | regex_match('(客厅|吸顶)') %}
            light.living_room
          {% elif item | regex_match('空调') %}
            switch.climate_living_room
          {% elif item | regex_match('热水') %}
            switch.water_heater
          {% endif %}

logbook:

# map:

sun:

sensor:
  - platform: season
    type: meteorological

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home

  # - platform: yr
  #   monitored_conditions:
  #     - humidity
  #     - symbol
  #     - temperature

tts:
  - platform: google

binary_sensor:
  # - platform: bayesian
  #   name: Occupancy living room
  #   prior: 0.5
  #   probability_threshold: 0.8
  #   device_class: occupancy
  #   observations:
  #     - platform: state
  #       entity_id: binary_sensor.motion_living_room
  #       prob_given_true: 0.9
  #       to_state: 'on'
  #     - platform: state
  #       entity_id: binary_sensor.motion_dining_room
  #       prob_given_true: 0.9
  #       to_state: 'on'
  #     - platform: state
  #       entity_id: binary_sensor.motion_sofas
  #       prob_given_true: 0.9
  #       to_state: 'on'

  - platform: mqtt
    name: mqtt_motion_sofas
    state_topic: motion/sofas
    device_class: motion

  - platform: template
    sensors:
      motion_sofas:
        friendly_name: Motion sofas
        value_template: >-
          {{ is_state('binary_sensor.mqtt_motion_sofas', 'on') }}
        delay_off: '00:05:00'
        device_class: motion

      occupancy_living_room:
        friendly_name: Occupancy living room
        value_template: >-
          {{ is_state('binary_sensor.motion_dining_room', 'on')
             or is_state('binary_sensor.motion_living_room', 'on')
             or is_state('binary_sensor.motion_sofas', 'on') }}
        device_class: occupancy

camera:
  - platform: mjpeg
    mjpeg_url: http://127.0.0.1:8081
    name: Living room

climate:
  - platform: xiaomi_miio
    name: AC partner
    host: !secret ac_partner_host
    token: !secret ac_partner_token
    target_sensor: sensor.ht_bedroom_temperature
    scan_interval: 60

  - platform: broadlink
    name: Bedroom
    host: !secret broadlink_host
    mac: !secret broadlink_mac
    ircodes_ini: broadlink_climate_codes/gree.ini
    target_temp: 26
    temp_sensor: sensor.ht_bedroom_temperature

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200

  - platform: ubus
    host: !secret ubus_host
    username: !secret ubus_username
    password: !secret ubus_password
    dhcp_software: none
    consider_home: 20
    new_device_defaults:
      track_new_devices: no

input_boolean:
  moonlight_living_room:
    name: Moonlight living room
    initial: no
    icon: mdi:weather-night

light:
  - platform: yeelight
    devices:
      !secret yeelight_host:
        name: Living room
        save_on_change: no
        transition: 1000

media_player:
  - platform: braviatv_psk
    name: TV
    host: !secret braviatv_host
    mac: !secret braviatv_mac
    psk: !secret braviatv_psk

mqtt:
  discovery: yes
  broker: 127.0.0.1
  username: local
  password: local
  birth_message:
    topic: hass/status
    payload: online
  will_message:
    topic: hass/status
    payload: offline

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

recorder:
  db_url: postgres://@/hass
  exclude:
    entities:
      - binary_sensor.mqtt_motion_sofas
      - climate.ac_partner
      - switch.tv
      - switch.climate_bedroom

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac

  - platform: flux
    name: flux_living_room
    lights:
      - light.living_room
    start_time: '7:00'
    stop_time: '23:00'
    start_colortemp: 5600
    sunset_colortemp: 4000
    stop_colortemp: 2700
    mode: mired

  - platform: template
    switches:
      climate_bedroom:
        friendly_name: Climate bedroom
        value_template: >-
          {{ not is_state_attr('climate.bedroom', 'operation_mode', 'off') }}
        icon_template: mdi:air-conditioner
        turn_on:
          service: climate.set_operation_mode
          data:
            entity_id: climate.bedroom
            operation_mode: cool
        turn_off:
          service: climate.set_operation_mode
          data:
            entity_id: climate.bedroom
            operation_mode: 'off'

      # dimming_living_room:
      #   friendly_name: Dimming living room
      #   value_template: >-
      #     {{ is_state('light.living_room', 'on') and is_state('switch.flux_living_room', 'off') and state_attr('light.living_room', 'brightness') <= 5 }}
      #   icon_template: mdi:book-open-page-variant
      #   turn_on:
      #     - service: switch.turn_off
      #       data:
      #         entity_id: switch.flux_living_room
      #     - service: light.yeelight_set_mode
      #       data:
      #         entity_id: light.living_room
      #         mode: moonlight
      #     - service: light.turn_on
      #       entity_id: light.living_room
      #       data:
      #         brightness: 255
      #   turn_off:
      #     service: switch.turn_on
      #     data:
      #       entity_id: switch.flux_living_room

      reading_living_room:
        friendly_name: Reading living room
        value_template: >-
          {{ is_state('light.living_room', 'on') and is_state('switch.flux_living_room', 'off') and state_attr('light.living_room', 'brightness') >= 160 }}
        icon_template: mdi:book-open-page-variant
        turn_on:
          - service: switch.turn_off
            data:
              entity_id: switch.flux_living_room
          - service: light.turn_on
            entity_id: light.living_room
            data:
              brightness: 162
              kelvin: 5000
              transition: 5
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.flux_living_room

      tv:
        friendly_name: TV
        value_template: >-
          {{ states('media_player.tv') }}
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.tv
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.tv
        icon_template: mdi:television

      water_heater:
        friendly_name: Water heater
        value_template: >-
          {{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}
        icon_template: mdi:fire
        turn_on:
          - alias: Power button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000005002C2251003600A801C403841388320001000101000000010000000001000100000101010001010101000100000000010001000101010100010410
          - delay: '00:00:01'
          - alias: Heating button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000006002E2254003600A801C403840D6C138832000100010100000001000000000100010000010101000101010101000100000001000001000101010001043205C0
          - wait_template: >-
              {{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}
            timeout: '00:01:03'
          - condition: template
            value_template: >-
              {{ state_attr('climate.ac_partner', 'load_power') | int < 100 }}
          - alias: Power button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000005002C2251003600A801C403841388320001000101000000010000000001000100000101010001010101000100000000010001000101010100010410
          - delay: '00:00:01'
          - alias: Heating button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000006002E2254003600A801C403840D6C138832000100010100000001000000000100010000010101000101010101000100000001000001000101010001043205C0
          - wait_template: >-
              {{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}
            timeout: '00:01:03'
          - condition: template
            value_template: >-
              {{ state_attr('climate.ac_partner', 'load_power') | int < 100 }}
          - alias: Power button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000005002C2251003600A801C403841388320001000101000000010000000001000100000101010001010101000100000000010001000101010100010410
          - delay: '00:00:01'
          - alias: Heating button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000006002E2254003600A801C403840D6C138832000100010100000001000000000100010000010101000101010101000100000001000001000101010001043205C0
        turn_off:
          - alias: Power button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000005002C2251003600A801C403841388320001000101000000010000000001000100000101010001010101000100000000010001000101010100010410

weather:
  - platform: yweather
    name: Hangzhou
    woeid: 2132574

web_speech:
  chrome_extra_args: --enable-low-end-device-mode --no-sandbox --single-process
  cleanup: yes
  lang: cmn-Hans-CN
  pulseaudio: yes
  xvfb: yes

xiaomi_aqara:
  interface: !secret interface
  gateways:
    - mac: !secret ac_partner_mac
      key: !secret ac_partner_key

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml

logger:
  default: warning
  logs:
    urllib3.connectionpool: critical
    custom_components.hotword_snowboy: debug
    custom_components.web_speech: debug
    # custom_components.climate.xiaomi_miio: debug
    # custom_components.rhasspy_train: debug
    # custom_components.stt_pocketsphinx: debug
    # homeassistant.components.binary_sensor.xiaomi_aqara: debug
    # homeassistant.components.xiaomi_aqara: debug
    # xiaomi_gateway: debug
