homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: Asia/Shanghai
  unit_system: metric
  customize: !include customize.yaml
  customize_domain:
    climate:
      icon: mdi:air-conditioner
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

config:

http:
  server_host: 127.0.0.1
  use_x_forwarded_for: yes
  trusted_proxies:
    - 127.0.0.1

updater:
  reporting: no

# discovery:

conversation:
  intents:
    TurnOnOff:
      - (?P<action>打开|关闭|关掉)(?P<name>.+)
    Query:
      - (?P<name>温度|室内温度|室内湿度|室外温度|室外湿度|天气|空气|空气质量)
      - 查看{name}
      - 查询{name}
    Rain:
      - '{name}会下雨吗'
    Know:
      - '{who}认识{thing}吗'
    Default:
      - '{name}'

history:

hotword_snowboy:
  model: snowboy/alexa.umdl
  sensitivity: 0.15
  apply_frontend: no

intent_script:
  Default:
    async_action: yes
    speech:
      text: &intent_default 不明白什么是{{ name }}
    action:
      - service: script.say
        data_template:
          message: *intent_default

  Know:
    async_action: yes
    speech:
      text: &intent_know >-
        {{ who }}不认识{{ thing }}
    action:
      - service: script.say
        data_template:
          message: *intent_know

  Query:
    async_action: yes
    speech:
      text: &intent_query >-
        {% if name == '温度' %}
          室内{{ states('sensor.ht_bedroom_temperature') | round }}度，湿度{{ states('sensor.ht_bedroom_humidity') | round }}%。室外{{ states('sensor.ht_outside_temperature') | round }}度，湿度{{ states('sensor.ht_outside_humidity') | round }}%
        {% elif name == '室内温度' %}
          室内{{ states('sensor.ht_bedroom_temperature') | round }}度
        {% elif name == '室内湿度' %}
          室内湿度{{ states('sensor.ht_bedroom_humidity') | round }}%
        {% elif name == '室外温度' %}
          室外{{ states('sensor.ht_outside_temperature') | round }}度
        {% elif name == '室外湿度' %}
          室外湿度{{ states('sensor.ht_outside_humidity') | round }}%
        {% elif name == '天气' %}
          当前{{ states('sensor.dark_sky_summary') }}，
          {% if now().hour <= 14 %}
            今天最高{{ states('sensor.dark_sky_daytime_high_apparent_temperature') | round }}度，
            {% set percent = states('sensor.dark_sky_precip_probability') | round %}
            {% if percent > 0 %}
              降水可能性{{ percent }}%。
            {% endif %}
          {% else %}
            明天最高{{ states('sensor.dark_sky_daytime_high_apparent_temperature_1') | round }}度，
            {% set percent = states('sensor.dark_sky_precip_probability_1') | round %}
            {% if percent > 0 %}
              降水可能性{{ percent }}%。
            {% endif %}
          {% endif %}
          {{ states('sensor.dark_sky_hourly_summary') }}
          未来一周{{ states('sensor.dark_sky_daily_summary') | regex_replace('°C', '度') }}
        {% elif name | regex_match('空气') %}
          {% set aqi = states('sensor.us_air_quality_index') | int %}
          当前空气质量
          {% if aqi == 0 %}
            未知
          {% elif aqi <= 50 %}
            优
          {% elif aqi <= 100 %}
            良
          {% elif aqi <= 150 %}
            轻度污染
          {% elif aqi <= 200 %}
            中度污染
          {% elif aqi <= 300 %}
            重度污染
          {% else %}
            严重污染
          {% endif %}
        {% else %}
          查询不到{{ name }}
        {% endif %}
    action:
      - service: script.say
        data_template:
          message: *intent_query

  Rain:
    async_action: yes
    speech:
      text: &intent_rain >-
        {% set map = {
          '今天': 'sensor.dark_sky_precip_probability',
          '明天': 'sensor.dark_sky_precip_probability_1'
        }%}
        {% set sensor = map[name] | default(None) %}
        {% if sensor %}
          {% set percent = states(sensor) | round %}
          {% if percent == 0 %}
            {{ name }}应该不会下雨
          {% else %}
            {{ name }}降水可能性{{ percent }}%
          {% endif %}
        {% else %}
          查询不到{{ name }}会不会下雨
        {% endif %}
    action:
      - service: script.say
        data_template:
          message: *intent_rain

  TurnOnOff:
    async_action: yes
    speech:
      text: &intent_turn_on_off >-
        {% if name | regex_match('电视|客厅|吸顶|卧室|空调|热水|阅读|看书|月光') %}
          已{{ action }}{{ name }}
        {% else %}
          找不到{{ name }}
        {% endif %}
    action:
      - service: script.say
        data_template:
          message: *intent_turn_on_off
      - service_template: homeassistant.turn_{% if action == '打开' %}on{% else %}off{% endif %}
        data_template:
          entity_id: >-
            {% if name | regex_match('电视') %}
              media_player.tv
            {% elif name | regex_match('客厅|吸顶') %}
              light.living_room
            {% elif name | regex_match('卧室') %}
              light.bedroom
            {% elif name | regex_match('空调') %}
              switch.climate_bedroom
            {% elif name | regex_match('热水') %}
              switch.water_heater
            {% elif name | regex_match('阅读|看书') %}
              switch.reading_living_room
            {% elif name | regex_match('月光') %}
              input_boolean.moonlight_living_room
            {% else %}
              input_boolean.dummy
            {% endif %}

logbook:

# map:

sun:

sensor:
  - platform: airvisual
    api_key: !secret airvisual_api_key
    monitored_conditions:
      - us
    show_on_map: no
    latitude: !secret alt_latitude
    longitude: !secret alt_longitude

  - platform: darksky
    latitude: !secret alt_latitude
    longitude: !secret alt_longitude
    language: zh
    api_key: !secret darksky_api_key
    scan_interval: '00:10:00'
    forecast:
      - 1
    monitored_conditions:
      - summary
      - precip_type
      - precip_probability
      - hourly_summary
      - daily_summary
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low

  - platform: season
    type: meteorological

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home

  # - platform: yr
  #   monitored_conditions:
  #     - humidity
  #     - symbol
  #     - temperature

tts:
  - platform: google
    language: zh

binary_sensor:
  # - platform: bayesian
  #   name: Occupancy living room
  #   prior: 0.5
  #   probability_threshold: 0.8
  #   device_class: occupancy
  #   observations:
  #     - platform: state
  #       entity_id: binary_sensor.motion_living_room
  #       prob_given_true: 0.9
  #       to_state: 'on'
  #     - platform: state
  #       entity_id: binary_sensor.motion_dining_room
  #       prob_given_true: 0.9
  #       to_state: 'on'
  #     - platform: state
  #       entity_id: binary_sensor.motion_sofas
  #       prob_given_true: 0.9
  #       to_state: 'on'

  - platform: mqtt
    name: mqtt_motion_sofas
    state_topic: motion/sofas
    device_class: motion

  - platform: template
    sensors:
      motion_sofas:
        friendly_name: Motion sofas
        value_template: >-
          {{ is_state('binary_sensor.mqtt_motion_sofas', 'on') }}
        delay_off: '00:05:00'
        device_class: motion

      occupancy_living_room:
        friendly_name: Occupancy living room
        entity_id:
          - binary_sensor.motion_dining_room
          - binary_sensor.motion_living_room
          - binary_sensor.motion_sofas
          - sensor.plug_power
        value_template: >-
          {% if is_state('binary_sensor.motion_dining_room', 'on')
             or is_state('binary_sensor.motion_living_room', 'on')
             or states('sensor.plug_power') | float >= 1 %}
            true
          {% elif is_state('binary_sensor.motion_dining_room', 'off')
             and is_state('binary_sensor.motion_living_room', 'off')
             and is_state('binary_sensor.motion_sofas', 'off') %}
            false
          {% else %}
            {{ states('binary_sensor.occupancy_living_room') }}
          {% endif %}
        device_class: occupancy

camera:
  - platform: mjpeg
    mjpeg_url: http://127.0.0.1:8081
    name: Living room

climate:
  - platform: xiaomi_miio
    name: AC partner
    host: !secret ac_partner_host
    token: !secret ac_partner_token
    target_sensor: sensor.ht_bedroom_temperature
    scan_interval: 60

  - platform: smartir
    name: Bedroom
    device_code: 1180
    controller_send_service: !secret broadlink_send_packet
    temperature_sensor: sensor.ht_bedroom_temperature
    humidity_sensor: sensor.ht_bedroom_humidity

device_tracker:
  - platform: ubus
    host: !secret ubus_host
    username: !secret ubus_username
    password: !secret ubus_password
    dhcp_software: none
    consider_home: 20
    new_device_defaults:
      track_new_devices: no

input_boolean:
  dummy:

  moonlight_living_room:
    name: Moonlight living room
    initial: no
    icon: mdi:weather-night

light:
  - platform: yeelight
    devices:
      !secret yeelight_living_room_host:
        name: Living room
        model: ceiling4
        save_on_change: no
        transition: 1000
      !secret yeelight_bedroom_host:
        name: Bedroom
        model: ceiling3
        save_on_change: no
        transition: 1000

media_player:
  - platform: braviatv_psk
    name: TV
    host: !secret braviatv_host
    mac: !secret braviatv_mac
    psk: !secret braviatv_psk

  - platform: vlc

mqtt:
  discovery: yes
  broker: 127.0.0.1
  username: local
  password: local
  birth_message:
    topic: hass/status
    payload: online
  will_message:
    topic: hass/status
    payload: offline

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

owntracks:
  max_gps_accuracy: 200

paplay:

recorder:
  db_url: postgres://@/hass
  exclude:
    entities:
      - binary_sensor.mqtt_motion_sofas
      - climate.ac_partner
      - switch.tv
      - switch.climate_bedroom

smartir:
  check_updates: no

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac

  - platform: template
    switches:
      climate_bedroom:
        friendly_name: Climate bedroom
        value_template: >-
          {{ not is_state_attr('climate.bedroom', 'operation_mode', 'off') }}
        icon_template: mdi:air-conditioner
        turn_on:
          service: climate.turn_on
          data:
            entity_id: climate.bedroom
        turn_off:
          service: climate.turn_off
          data:
            entity_id: climate.bedroom

      light_living_room:
        friendly_name: Light living room
        value_template: >-
          {{ states('light.living_room') }}
        turn_on:
          service: light.turn_on
          data_template:
            entity_id: light.living_room
            brightness: >-
              {% if now().hour >= 7 and now().hour < 23 %}
                240
              {% else %}
                1
              {% endif %}
            kelvin: >-
              {% if now().hour >= 7 and now().hour < 23 %}
                5000
              {% else %}
                2700
              {% endif %}
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.living_room

      reading_living_room:
        friendly_name: Reading living room
        value_template: >-
          {{ is_state('light.living_room', 'on') and state_attr('light.living_room', 'brightness') >= 200 }}
        icon_template: mdi:book-open-page-variant
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.living_room
            brightness: 240
            kelvin: 5000
            transition: 5
        turn_off:
          service: light.turn_on
          data:
            entity_id: light.living_room
            brightness: 162
            kelvin: 5000
            transition: 5

      tv:
        friendly_name: TV
        value_template: >-
          {{ states('media_player.tv') }}
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.tv
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.tv
        icon_template: mdi:television

      water_heater:
        friendly_name: Water heater
        value_template: >-
          {{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}
        icon_template: mdi:fire
        turn_on:
          - &water_heater_condition
            condition: template
            value_template: >-
              {{ state_attr('climate.ac_partner', 'load_power') | int < 100 }}
          - &water_heater_heating
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000006002E2254003600A901C403860D6D138832000100010100000001000000000100010000010101000101010101000100000001000001000101010001043205C4
          - &water_heater_wait
            wait_template: >-
              {{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}
            timeout: '00:01:03'
          - *water_heater_condition
          - &water_heater_power
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000005002C2251003600A801C403841388320001000101000000010000000001000100000101010001010101000100000000010001000101010100010410
          - &water_heater_delay
            delay: '00:00:01'
          - *water_heater_heating
          - *water_heater_wait
          - *water_heater_condition
          - *water_heater_power
          - *water_heater_delay
          - *water_heater_heating
        turn_off:
          - condition: template
            value_template: >-
              {{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}
          - *water_heater_heating

weather:
  - platform: darksky
    name: Hangzhou
    mode: daily
    api_key: !secret darksky_api_key
    latitude: !secret alt_latitude
    longitude: !secret alt_longitude

web_speech:
  chrome_extra_args: --enable-low-end-device-mode --no-sandbox
  cleanup: yes
  lang: cmn-Hans-CN
  pulseaudio: yes
  xvfb: yes

xiaomi_aqara:
  interface: !secret interface
  gateways:
    - mac: !secret ac_partner_mac
      key: !secret ac_partner_key

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml

logger:
  default: warning
  logs:
    custom_components.hotword_snowboy: debug
    custom_components.web_speech: debug
    homeassistant.components.light.yeelight: critical
    urllib3.connectionpool: critical
    # custom_components.climate.xiaomi_miio: debug
    # custom_components.rhasspy_train: debug
    # custom_components.stt_pocketsphinx: debug
    # homeassistant.components.binary_sensor.xiaomi_aqara: debug
    # homeassistant.components.xiaomi_aqara: debug
    # xiaomi_gateway: debug
